/* Generated by tools/generate_shaders.ae - do not edit. */
#ifndef AE3D_VK_UNIFORMS_H
#define AE3D_VK_UNIFORMS_H

#include <string.h>

#define AE3D_VK_SCENE_SIZE 9168

/* std140 layout, offsets computed from the same declarations the shader
   block is generated from, so the two cannot disagree. */
typedef struct {
    unsigned char bytes[9168];
} ae3d_vk_scene;

#define AE3D_VK_OFF_ISINSTANCED 1280
#define AE3D_VK_OFF_USEINSTANCECOLOR 1284
#define AE3D_VK_OFF_INSTANCEPOINTS 1288
#define AE3D_VK_OFF_INSTANCEBILLBOARD 1292
#define AE3D_VK_OFF_VIEWPOS 1296
#define AE3D_VK_OFF_MODEL 1312
#define AE3D_VK_OFF_VIEWPROJECTION 1376
#define AE3D_VK_OFF_LIGHTSPACEMATRIX 1440
#define AE3D_VK_OFF_PREVMODEL 1504
#define AE3D_VK_OFF_PREVVIEWPROJECTION 1568
#define AE3D_VK_OFF_ISSKINNED 1632
#define AE3D_VK_OFF_BONES 1648
#define AE3D_VK_OFF_JITTER 7792
#define AE3D_VK_OFF_SCREENSIZE 7800
#define AE3D_VK_OFF_LIGHTCOUNT 7808
#define AE3D_VK_OFF_CLUSTERDIMS 7824
#define AE3D_VK_OFF_CLUSTERDEPTH 7840
#define AE3D_VK_OFF_CLUSTERVIEWPROJECTION 7856
#define AE3D_VK_OFF_CLUSTERFORWARD 7920
#define AE3D_VK_OFF_IMPOSTOR 7936
#define AE3D_VK_OFF_CAPTURECHANNEL 7940
#define AE3D_VK_OFF_VIEWDISTANCE 7944
#define AE3D_VK_OFF_DIFFUSECOLOR 7952
#define AE3D_VK_OFF_SPECULARCOLOR 7968
#define AE3D_VK_OFF_METALLIC 7980
#define AE3D_VK_OFF_ROUGHNESS 7984
#define AE3D_VK_OFF_EXPOSURE 7988
#define AE3D_VK_OFF_CLOUDCOVER 7992
#define AE3D_VK_OFF_CLOUDTIME 7996
#define AE3D_VK_OFF_CLOUDSUN 8000
#define AE3D_VK_OFF_MATERIALALPHA 8012
#define AE3D_VK_OFF_REFLECTIVITY 8016
#define AE3D_VK_OFF_WETNESS 8020
#define AE3D_VK_OFF_FRAMEEXPOSURE 8024
#define AE3D_VK_OFF_HASNORMALMAP 8028
#define AE3D_VK_OFF_NORMALSTRENGTH 8032
#define AE3D_VK_OFF_OCCLUSIONSTRENGTH 8036
#define AE3D_VK_OFF_ENABLECLEARCOAT 8040
#define AE3D_VK_OFF_CLEARCOATROUGHNESS 8044
#define AE3D_VK_OFF_CLEARCOATINTENSITY 8048
#define AE3D_VK_OFF_ENABLESHEEN 8052
#define AE3D_VK_OFF_SHEENCOLOR 8064
#define AE3D_VK_OFF_SHEENROUGHNESS 8076
#define AE3D_VK_OFF_ENABLETRANSMISSION 8080
#define AE3D_VK_OFF_TRANSMISSIONFACTOR 8084
#define AE3D_VK_OFF_ENABLEMULTIPLESCATTERING 8088
#define AE3D_VK_OFF_ENABLEENERGYCONSERVATION 8092
#define AE3D_VK_OFF_ENABLEIMAGEBASEDLIGHTING 8096
#define AE3D_VK_OFF_IBLINTENSITY 8100
#define AE3D_VK_OFF_ENABLEVOLUMETRICLIGHTING 8104
#define AE3D_VK_OFF_VOLUMETRICINTENSITY 8108
#define AE3D_VK_OFF_VOLUMETRICSTEPS 8112
#define AE3D_VK_OFF_VOLUMETRICSCATTERING 8116
#define AE3D_VK_OFF_ENABLEGLOBALILLUMINATION 8120
#define AE3D_VK_OFF_GIINTENSITY 8124
#define AE3D_VK_OFF_GIBOUNCES 8128
#define AE3D_VK_OFF_ENABLEBLOOM 8132
#define AE3D_VK_OFF_BLOOMTHRESHOLD 8136
#define AE3D_VK_OFF_BLOOMINTENSITY 8140
#define AE3D_VK_OFF_ENABLEFOG 8144
#define AE3D_VK_OFF_FOGSTART 8148
#define AE3D_VK_OFF_FOGEND 8152
#define AE3D_VK_OFF_FOGCOLOR 8160
#define AE3D_VK_OFF_FOGINTENSITY 8172
#define AE3D_VK_OFF_ENABLESHADOWS 8176
#define AE3D_VK_OFF_HASSHADOWMAP 8180
#define AE3D_VK_OFF_SHADOWINTENSITY 8184
#define AE3D_VK_OFF_SHADOWSOFTNESS 8188
#define AE3D_VK_OFF_SHADOWDIRECTION 8192
#define AE3D_VK_OFF_SHADOWTEXELWORLD 8204
#define AE3D_VK_OFF_RAYSHADOWS 8208
#define AE3D_VK_OFF_SUNANGLE 8212
#define AE3D_VK_OFF_RAYOCCLUSION 8216
#define AE3D_VK_OFF_RAYOCCLUSIONSTRENGTH 8220
#define AE3D_VK_OFF_RAYLAMPRADIUS 8224
#define AE3D_VK_OFF_RAYREACH 8228
#define AE3D_VK_OFF_RAYFRAME 8232
#define AE3D_VK_OFF_ENABLEPERLINNOISE 8236
#define AE3D_VK_OFF_NOISESCALE 8240
#define AE3D_VK_OFF_NOISEOCTAVES 8244
#define AE3D_VK_OFF_NOISEINTENSITY 8248
#define AE3D_VK_OFF_ENABLECAUSTICS 8252
#define AE3D_VK_OFF_CAUSTICSINTENSITY 8256
#define AE3D_VK_OFF_CAUSTICSSCALE 8260
#define AE3D_VK_OFF_CAUSTICSSPEED 8264
#define AE3D_VK_OFF_CAUSTICSWATERLEVEL 8268
#define AE3D_VK_OFF_CAUSTICSDEPTH 8272
#define AE3D_VK_OFF_CAUSTICSTIME 8276
#define AE3D_VK_OFF_PROJECTION 8288
#define AE3D_VK_OFF_VIEW 8352
#define AE3D_VK_OFF_CLOUDSUNCOLOR 8416
#define AE3D_VK_OFF_CLOUDFRAME 8428
#define AE3D_VK_OFF_SKYPROCEDURAL 8432
#define AE3D_VK_OFF_SKYOVERCAST 8436
#define AE3D_VK_OFF_SKYOVERCASTCOLOR 8448
#define AE3D_VK_OFF_TEXELSIZE 8464
#define AE3D_VK_OFF_EDGETHRESHOLD 8472
#define AE3D_VK_OFF_EDGETHRESHOLDMIN 8476
#define AE3D_VK_OFF_SUBPIXELQUALITY 8480
#define AE3D_VK_OFF_INVVIEWPROJECTION 8496
#define AE3D_VK_OFF_SSRROADHEIGHT 8560
#define AE3D_VK_OFF_SSRSTRENGTH 8564
#define AE3D_VK_OFF_SSAORADIUS 8568
#define AE3D_VK_OFF_SSAOINTENSITY 8572
#define AE3D_VK_OFF_DEPTHSAMPLECOUNT 8576
#define AE3D_VK_OFF_TAABLEND 8580
#define AE3D_VK_OFF_TIME 8584
#define AE3D_VK_OFF_WAVESPEEDMULTIPLIER 8588
#define AE3D_VK_OFF_WAVEHEIGHTMULTIPLIER 8592
#define AE3D_VK_OFF_WAVERANDOMNESS 8596
#define AE3D_VK_OFF_WAVEDIRECTIONS 8608
#define AE3D_VK_OFF_WAVEAMPLITUDES 8672
#define AE3D_VK_OFF_WAVEFREQUENCIES 8736
#define AE3D_VK_OFF_WAVESPEEDS 8800
#define AE3D_VK_OFF_WAVEPHASES 8864
#define AE3D_VK_OFF_WAVESTEEPNESS 8928
#define AE3D_VK_OFF_LIGHTPOS 8992
#define AE3D_VK_OFF_LIGHTDIRECTION 9008
#define AE3D_VK_OFF_LIGHTCOLOR 9024
#define AE3D_VK_OFF_LIGHTINTENSITY 9036
#define AE3D_VK_OFF_WATERBASECOLOR 9040
#define AE3D_VK_OFF_WATEROPACITY 9052
#define AE3D_VK_OFF_ENABLEFOAM 9056
#define AE3D_VK_OFF_FOAMINTENSITY 9060
#define AE3D_VK_OFF_WATERPLANEHEIGHT 9064
#define AE3D_VK_OFF_WATERLEVEL 9068
#define AE3D_VK_OFF_SKYCOLOR 9072
#define AE3D_VK_OFF_HORIZONCOLOR 9088
#define AE3D_VK_OFF_ENABLEWATERREFLECTION 9100
#define AE3D_VK_OFF_WATERREFLECTIONINTENSITY 9104
#define AE3D_VK_OFF_HASSKYTEXTURE 9108
#define AE3D_VK_OFF_HASSCENEDEPTH 9112
#define AE3D_VK_OFF_WATERDEPTHFADE 9116
#define AE3D_VK_OFF_WATERSHOREFOAM 9120
#define AE3D_VK_OFF_ENABLEWATERDISTORTION 9124
#define AE3D_VK_OFF_WATERDISTORTIONINTENSITY 9128
#define AE3D_VK_OFF_ENABLEWATERNORMALMAPPING 9132
#define AE3D_VK_OFF_WATERNORMALINTENSITY 9136
#define AE3D_VK_OFF_POSEBANKFRAMES 9140
#define AE3D_VK_OFF_IMPOSTORCOLS 9144
#define AE3D_VK_OFF_IMPOSTORROWS 9148
#define AE3D_VK_OFF_IMPOSTORWIDTH 9152
#define AE3D_VK_OFF_IMPOSTORHEIGHT 9156
#define AE3D_VK_OFF_CROWDTRAVEL 9160
#define AE3D_VK_OFF_CROWDPHASESTEP 9164

#define AE3D_VK_MAX_LIGHTS 16
#define AE3D_VK_LIGHT_STRIDE 80
#define AE3D_VK_LIGHT_POSITION 0
#define AE3D_VK_LIGHT_COLOR 16
#define AE3D_VK_LIGHT_INTENSITY 28
#define AE3D_VK_LIGHT_AMBIENTSTRENGTH 32
#define AE3D_VK_LIGHT_TEMPERATURE 36
#define AE3D_VK_LIGHT_ISDIRECTIONAL 40
#define AE3D_VK_LIGHT_DIRECTION 48
#define AE3D_VK_LIGHT_CONSTANTATTEN 60
#define AE3D_VK_LIGHT_LINEARATTEN 64
#define AE3D_VK_LIGHT_QUADRATICATTEN 68
#define AE3D_VK_LIGHT_SPOTCOSOUTER 72
#define AE3D_VK_LIGHT_SPOTCOSINNER 76

typedef struct {
    const char *name;
    int offset;
} ae3d_vk_uniform_slot;

static const ae3d_vk_uniform_slot ae3d_vk_uniform_slots[] = {
    { "bloomIntensity", 8140 },
    { "bloomThreshold", 8136 },
    { "bones", 1648 },
    { "captureChannel", 7940 },
    { "causticsDepth", 8272 },
    { "causticsIntensity", 8256 },
    { "causticsScale", 8260 },
    { "causticsSpeed", 8264 },
    { "causticsTime", 8276 },
    { "causticsWaterLevel", 8268 },
    { "clearcoatIntensity", 8048 },
    { "clearcoatRoughness", 8044 },
    { "cloudCover", 7992 },
    { "cloudFrame", 8428 },
    { "cloudSun", 8000 },
    { "cloudSunColor", 8416 },
    { "cloudTime", 7996 },
    { "clusterDepth", 7840 },
    { "clusterDims", 7824 },
    { "clusterForward", 7920 },
    { "clusterViewProjection", 7856 },
    { "crowdPhaseStep", 9164 },
    { "crowdTravel", 9160 },
    { "depthSampleCount", 8576 },
    { "diffuseColor", 7952 },
    { "edgeThreshold", 8472 },
    { "edgeThresholdMin", 8476 },
    { "enableBloom", 8132 },
    { "enableCaustics", 8252 },
    { "enableClearcoat", 8040 },
    { "enableEnergyConservation", 8092 },
    { "enableFoam", 9056 },
    { "enableFog", 8144 },
    { "enableGlobalIllumination", 8120 },
    { "enableImageBasedLighting", 8096 },
    { "enableMultipleScattering", 8088 },
    { "enablePerlinNoise", 8236 },
    { "enableShadows", 8176 },
    { "enableSheen", 8052 },
    { "enableTransmission", 8080 },
    { "enableVolumetricLighting", 8104 },
    { "enableWaterDistortion", 9124 },
    { "enableWaterNormalMapping", 9132 },
    { "enableWaterReflection", 9100 },
    { "exposure", 7988 },
    { "foamIntensity", 9060 },
    { "fogColor", 8160 },
    { "fogEnd", 8152 },
    { "fogIntensity", 8172 },
    { "fogStart", 8148 },
    { "frameExposure", 8024 },
    { "giBounces", 8128 },
    { "giIntensity", 8124 },
    { "hasNormalMap", 8028 },
    { "hasSceneDepth", 9112 },
    { "hasShadowMap", 8180 },
    { "hasSkyTexture", 9108 },
    { "horizonColor", 9088 },
    { "iblIntensity", 8100 },
    { "impostor", 7936 },
    { "impostorCols", 9144 },
    { "impostorHeight", 9156 },
    { "impostorRows", 9148 },
    { "impostorWidth", 9152 },
    { "instanceBillboard", 1292 },
    { "instancePoints", 1288 },
    { "invViewProjection", 8496 },
    { "isInstanced", 1280 },
    { "isSkinned", 1632 },
    { "jitter", 7792 },
    { "lightColor", 9024 },
    { "lightCount", 7808 },
    { "lightDirection", 9008 },
    { "lightIntensity", 9036 },
    { "lightPos", 8992 },
    { "lightSpaceMatrix", 1440 },
    { "materialAlpha", 8012 },
    { "metallic", 7980 },
    { "model", 1312 },
    { "noiseIntensity", 8248 },
    { "noiseOctaves", 8244 },
    { "noiseScale", 8240 },
    { "normalStrength", 8032 },
    { "occlusionStrength", 8036 },
    { "poseBankFrames", 9140 },
    { "prevModel", 1504 },
    { "prevViewProjection", 1568 },
    { "projection", 8288 },
    { "rayFrame", 8232 },
    { "rayLampRadius", 8224 },
    { "rayOcclusion", 8216 },
    { "rayOcclusionStrength", 8220 },
    { "rayReach", 8228 },
    { "rayShadows", 8208 },
    { "reflectivity", 8016 },
    { "roughness", 7984 },
    { "screenSize", 7800 },
    { "shadowDirection", 8192 },
    { "shadowIntensity", 8184 },
    { "shadowSoftness", 8188 },
    { "shadowTexelWorld", 8204 },
    { "sheenColor", 8064 },
    { "sheenRoughness", 8076 },
    { "skyColor", 9072 },
    { "skyOvercast", 8436 },
    { "skyOvercastColor", 8448 },
    { "skyProcedural", 8432 },
    { "specularColor", 7968 },
    { "ssaoIntensity", 8572 },
    { "ssaoRadius", 8568 },
    { "ssrRoadHeight", 8560 },
    { "ssrStrength", 8564 },
    { "subpixelQuality", 8480 },
    { "sunAngle", 8212 },
    { "taaBlend", 8580 },
    { "texelSize", 8464 },
    { "time", 8584 },
    { "transmissionFactor", 8084 },
    { "useInstanceColor", 1284 },
    { "view", 8352 },
    { "viewDistance", 7944 },
    { "viewPos", 1296 },
    { "viewProjection", 1376 },
    { "volumetricIntensity", 8108 },
    { "volumetricScattering", 8116 },
    { "volumetricSteps", 8112 },
    { "waterBaseColor", 9040 },
    { "waterDepthFade", 9116 },
    { "waterDistortionIntensity", 9128 },
    { "waterLevel", 9068 },
    { "waterNormalIntensity", 9136 },
    { "waterOpacity", 9052 },
    { "waterPlaneHeight", 9064 },
    { "waterReflectionIntensity", 9104 },
    { "waterShoreFoam", 9120 },
    { "waveAmplitudes", 8672 },
    { "waveDirections", 8608 },
    { "waveFrequencies", 8736 },
    { "waveHeightMultiplier", 8592 },
    { "wavePhases", 8864 },
    { "waveRandomness", 8596 },
    { "waveSpeedMultiplier", 8588 },
    { "waveSpeeds", 8800 },
    { "waveSteepness", 8928 },
    { "wetness", 8020 },
};

#define AE3D_VK_UNIFORM_SLOT_COUNT 145

static inline int ae3d_vk_uniform_offset(const char *name) {
    int low = 0;
    int high = AE3D_VK_UNIFORM_SLOT_COUNT - 1;
    if (!name) return -1;
    while (low <= high) {
        int mid = (low + high) / 2;
        int order = strcmp(name, ae3d_vk_uniform_slots[mid].name);
        if (order == 0) return ae3d_vk_uniform_slots[mid].offset;
        if (order < 0) high = mid - 1; else low = mid + 1;
    }
    return -1;
}

static inline void ae3d_vk_set_float(ae3d_vk_scene *s, int offset, float v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_int(ae3d_vk_scene *s, int offset, int v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_vec3(ae3d_vk_scene *s, int offset, double x, double y, double z) {
    float v[3];
    v[0] = (float)x; v[1] = (float)y; v[2] = (float)z;
    memcpy(s->bytes + offset, v, sizeof(v));
}
static inline void ae3d_vk_set_mat4(ae3d_vk_scene *s, int offset, const double *m) {
    float v[16];
    int i;
    for (i = 0; i < 16; i++) v[i] = (float)m[i];
    memcpy(s->bytes + offset, v, sizeof(v));
}

#endif
