/* Generated by tools/generate_shaders.ae - do not edit. */
#ifndef AE3D_VK_UNIFORMS_H
#define AE3D_VK_UNIFORMS_H

#include <string.h>

#define AE3D_VK_SCENE_SIZE 9456

/* std140 layout, offsets computed from the same declarations the shader
   block is generated from, so the two cannot disagree. */
typedef struct {
    unsigned char bytes[9456];
} ae3d_vk_scene;

#define AE3D_VK_OFF_ISINSTANCED 1280
#define AE3D_VK_OFF_USEINSTANCECOLOR 1284
#define AE3D_VK_OFF_INSTANCEPOINTS 1288
#define AE3D_VK_OFF_INSTANCEBILLBOARD 1292
#define AE3D_VK_OFF_VIEWPOS 1296
#define AE3D_VK_OFF_MODEL 1312
#define AE3D_VK_OFF_VIEWPROJECTION 1376
#define AE3D_VK_OFF_LIGHTSPACEMATRIX 1440
#define AE3D_VK_OFF_PREVMODEL 1504
#define AE3D_VK_OFF_PREVVIEWPROJECTION 1568
#define AE3D_VK_OFF_ISSKINNED 1632
#define AE3D_VK_OFF_BONES 1648
#define AE3D_VK_OFF_JITTER 7792
#define AE3D_VK_OFF_SCREENSIZE 7800
#define AE3D_VK_OFF_LIGHTCOUNT 7808
#define AE3D_VK_OFF_CLUSTERDIMS 7824
#define AE3D_VK_OFF_CLUSTERDEPTH 7840
#define AE3D_VK_OFF_CLUSTERVIEWPROJECTION 7856
#define AE3D_VK_OFF_VIEWDEPTH 7920
#define AE3D_VK_OFF_IMPOSTOR 7936
#define AE3D_VK_OFF_CAPTURECHANNEL 7940
#define AE3D_VK_OFF_VIEWDISTANCE 7944
#define AE3D_VK_OFF_DIFFUSECOLOR 7952
#define AE3D_VK_OFF_SPECULARCOLOR 7968
#define AE3D_VK_OFF_METALLIC 7980
#define AE3D_VK_OFF_ROUGHNESS 7984
#define AE3D_VK_OFF_EXPOSURE 7988
#define AE3D_VK_OFF_CLOUDCOVER 7992
#define AE3D_VK_OFF_CLOUDTIME 7996
#define AE3D_VK_OFF_CLOUDSUN 8000
#define AE3D_VK_OFF_MATERIALALPHA 8012
#define AE3D_VK_OFF_REFLECTIVITY 8016
#define AE3D_VK_OFF_WETNESS 8020
#define AE3D_VK_OFF_FRAMEEXPOSURE 8024
#define AE3D_VK_OFF_HASNORMALMAP 8028
#define AE3D_VK_OFF_NORMALSTRENGTH 8032
#define AE3D_VK_OFF_OCCLUSIONSTRENGTH 8036
#define AE3D_VK_OFF_ENABLECLEARCOAT 8040
#define AE3D_VK_OFF_CLEARCOATROUGHNESS 8044
#define AE3D_VK_OFF_CLEARCOATINTENSITY 8048
#define AE3D_VK_OFF_ENABLESHEEN 8052
#define AE3D_VK_OFF_SHEENCOLOR 8064
#define AE3D_VK_OFF_SHEENROUGHNESS 8076
#define AE3D_VK_OFF_ENABLETRANSMISSION 8080
#define AE3D_VK_OFF_TRANSMISSIONFACTOR 8084
#define AE3D_VK_OFF_ENABLEMULTIPLESCATTERING 8088
#define AE3D_VK_OFF_ENABLEENERGYCONSERVATION 8092
#define AE3D_VK_OFF_ENABLEIMAGEBASEDLIGHTING 8096
#define AE3D_VK_OFF_IBLINTENSITY 8100
#define AE3D_VK_OFF_ENABLEVOLUMETRICLIGHTING 8104
#define AE3D_VK_OFF_VOLUMETRICINTENSITY 8108
#define AE3D_VK_OFF_VOLUMETRICSTEPS 8112
#define AE3D_VK_OFF_VOLUMETRICSCATTERING 8116
#define AE3D_VK_OFF_ENABLEGLOBALILLUMINATION 8120
#define AE3D_VK_OFF_GIINTENSITY 8124
#define AE3D_VK_OFF_GIBOUNCES 8128
#define AE3D_VK_OFF_ENABLEBLOOM 8132
#define AE3D_VK_OFF_BLOOMTHRESHOLD 8136
#define AE3D_VK_OFF_BLOOMINTENSITY 8140
#define AE3D_VK_OFF_ENABLEFOG 8144
#define AE3D_VK_OFF_FOGSTART 8148
#define AE3D_VK_OFF_FOGEND 8152
#define AE3D_VK_OFF_FOGCOLOR 8160
#define AE3D_VK_OFF_FOGINTENSITY 8172
#define AE3D_VK_OFF_ENABLESHADOWS 8176
#define AE3D_VK_OFF_HASSHADOWMAP 8180
#define AE3D_VK_OFF_SHADOWINTENSITY 8184
#define AE3D_VK_OFF_SHADOWSOFTNESS 8188
#define AE3D_VK_OFF_SHADOWDIRECTION 8192
#define AE3D_VK_OFF_CASCADEMATRICES 8208
#define AE3D_VK_OFF_CASCADESPLITS 8464
#define AE3D_VK_OFF_CASCADETEXELWORLD 8480
#define AE3D_VK_OFF_CASCADECOUNT 8496
#define AE3D_VK_OFF_RAYSHADOWS 8500
#define AE3D_VK_OFF_SUNANGLE 8504
#define AE3D_VK_OFF_RAYOCCLUSION 8508
#define AE3D_VK_OFF_RAYOCCLUSIONSTRENGTH 8512
#define AE3D_VK_OFF_RAYLAMPRADIUS 8516
#define AE3D_VK_OFF_RAYREACH 8520
#define AE3D_VK_OFF_RAYFRAME 8524
#define AE3D_VK_OFF_ENABLEPERLINNOISE 8528
#define AE3D_VK_OFF_NOISESCALE 8532
#define AE3D_VK_OFF_NOISEOCTAVES 8536
#define AE3D_VK_OFF_NOISEINTENSITY 8540
#define AE3D_VK_OFF_ENABLECAUSTICS 8544
#define AE3D_VK_OFF_CAUSTICSINTENSITY 8548
#define AE3D_VK_OFF_CAUSTICSSCALE 8552
#define AE3D_VK_OFF_CAUSTICSSPEED 8556
#define AE3D_VK_OFF_CAUSTICSWATERLEVEL 8560
#define AE3D_VK_OFF_CAUSTICSDEPTH 8564
#define AE3D_VK_OFF_CAUSTICSTIME 8568
#define AE3D_VK_OFF_PROJECTION 8576
#define AE3D_VK_OFF_VIEW 8640
#define AE3D_VK_OFF_CLOUDSUNCOLOR 8704
#define AE3D_VK_OFF_CLOUDFRAME 8716
#define AE3D_VK_OFF_SKYPROCEDURAL 8720
#define AE3D_VK_OFF_SKYOVERCAST 8724
#define AE3D_VK_OFF_SKYOVERCASTCOLOR 8736
#define AE3D_VK_OFF_TEXELSIZE 8752
#define AE3D_VK_OFF_EDGETHRESHOLD 8760
#define AE3D_VK_OFF_EDGETHRESHOLDMIN 8764
#define AE3D_VK_OFF_SUBPIXELQUALITY 8768
#define AE3D_VK_OFF_INVVIEWPROJECTION 8784
#define AE3D_VK_OFF_SSRROADHEIGHT 8848
#define AE3D_VK_OFF_SSRSTRENGTH 8852
#define AE3D_VK_OFF_SSAORADIUS 8856
#define AE3D_VK_OFF_SSAOINTENSITY 8860
#define AE3D_VK_OFF_DEPTHSAMPLECOUNT 8864
#define AE3D_VK_OFF_TAABLEND 8868
#define AE3D_VK_OFF_TIME 8872
#define AE3D_VK_OFF_WAVESPEEDMULTIPLIER 8876
#define AE3D_VK_OFF_WAVEHEIGHTMULTIPLIER 8880
#define AE3D_VK_OFF_WAVERANDOMNESS 8884
#define AE3D_VK_OFF_WAVEDIRECTIONS 8896
#define AE3D_VK_OFF_WAVEAMPLITUDES 8960
#define AE3D_VK_OFF_WAVEFREQUENCIES 9024
#define AE3D_VK_OFF_WAVESPEEDS 9088
#define AE3D_VK_OFF_WAVEPHASES 9152
#define AE3D_VK_OFF_WAVESTEEPNESS 9216
#define AE3D_VK_OFF_LIGHTPOS 9280
#define AE3D_VK_OFF_LIGHTDIRECTION 9296
#define AE3D_VK_OFF_LIGHTCOLOR 9312
#define AE3D_VK_OFF_LIGHTINTENSITY 9324
#define AE3D_VK_OFF_WATERBASECOLOR 9328
#define AE3D_VK_OFF_WATEROPACITY 9340
#define AE3D_VK_OFF_ENABLEFOAM 9344
#define AE3D_VK_OFF_FOAMINTENSITY 9348
#define AE3D_VK_OFF_WATERPLANEHEIGHT 9352
#define AE3D_VK_OFF_WATERLEVEL 9356
#define AE3D_VK_OFF_SKYCOLOR 9360
#define AE3D_VK_OFF_HORIZONCOLOR 9376
#define AE3D_VK_OFF_ENABLEWATERREFLECTION 9388
#define AE3D_VK_OFF_WATERREFLECTIONINTENSITY 9392
#define AE3D_VK_OFF_HASSKYTEXTURE 9396
#define AE3D_VK_OFF_HASSCENEDEPTH 9400
#define AE3D_VK_OFF_WATERDEPTHFADE 9404
#define AE3D_VK_OFF_WATERSHOREFOAM 9408
#define AE3D_VK_OFF_ENABLEWATERDISTORTION 9412
#define AE3D_VK_OFF_WATERDISTORTIONINTENSITY 9416
#define AE3D_VK_OFF_ENABLEWATERNORMALMAPPING 9420
#define AE3D_VK_OFF_WATERNORMALINTENSITY 9424
#define AE3D_VK_OFF_POSEBANKFRAMES 9428
#define AE3D_VK_OFF_IMPOSTORCOLS 9432
#define AE3D_VK_OFF_IMPOSTORROWS 9436
#define AE3D_VK_OFF_IMPOSTORWIDTH 9440
#define AE3D_VK_OFF_IMPOSTORHEIGHT 9444
#define AE3D_VK_OFF_CROWDTRAVEL 9448
#define AE3D_VK_OFF_CROWDPHASESTEP 9452

#define AE3D_VK_MAX_LIGHTS 16
#define AE3D_VK_LIGHT_STRIDE 80
#define AE3D_VK_LIGHT_POSITION 0
#define AE3D_VK_LIGHT_COLOR 16
#define AE3D_VK_LIGHT_INTENSITY 28
#define AE3D_VK_LIGHT_AMBIENTSTRENGTH 32
#define AE3D_VK_LIGHT_TEMPERATURE 36
#define AE3D_VK_LIGHT_ISDIRECTIONAL 40
#define AE3D_VK_LIGHT_DIRECTION 48
#define AE3D_VK_LIGHT_CONSTANTATTEN 60
#define AE3D_VK_LIGHT_LINEARATTEN 64
#define AE3D_VK_LIGHT_QUADRATICATTEN 68
#define AE3D_VK_LIGHT_SPOTCOSOUTER 72
#define AE3D_VK_LIGHT_SPOTCOSINNER 76

typedef struct {
    const char *name;
    int offset;
} ae3d_vk_uniform_slot;

static const ae3d_vk_uniform_slot ae3d_vk_uniform_slots[] = {
    { "bloomIntensity", 8140 },
    { "bloomThreshold", 8136 },
    { "bones", 1648 },
    { "captureChannel", 7940 },
    { "cascadeCount", 8496 },
    { "cascadeMatrices", 8208 },
    { "cascadeSplits", 8464 },
    { "cascadeTexelWorld", 8480 },
    { "causticsDepth", 8564 },
    { "causticsIntensity", 8548 },
    { "causticsScale", 8552 },
    { "causticsSpeed", 8556 },
    { "causticsTime", 8568 },
    { "causticsWaterLevel", 8560 },
    { "clearcoatIntensity", 8048 },
    { "clearcoatRoughness", 8044 },
    { "cloudCover", 7992 },
    { "cloudFrame", 8716 },
    { "cloudSun", 8000 },
    { "cloudSunColor", 8704 },
    { "cloudTime", 7996 },
    { "clusterDepth", 7840 },
    { "clusterDims", 7824 },
    { "clusterViewProjection", 7856 },
    { "crowdPhaseStep", 9452 },
    { "crowdTravel", 9448 },
    { "depthSampleCount", 8864 },
    { "diffuseColor", 7952 },
    { "edgeThreshold", 8760 },
    { "edgeThresholdMin", 8764 },
    { "enableBloom", 8132 },
    { "enableCaustics", 8544 },
    { "enableClearcoat", 8040 },
    { "enableEnergyConservation", 8092 },
    { "enableFoam", 9344 },
    { "enableFog", 8144 },
    { "enableGlobalIllumination", 8120 },
    { "enableImageBasedLighting", 8096 },
    { "enableMultipleScattering", 8088 },
    { "enablePerlinNoise", 8528 },
    { "enableShadows", 8176 },
    { "enableSheen", 8052 },
    { "enableTransmission", 8080 },
    { "enableVolumetricLighting", 8104 },
    { "enableWaterDistortion", 9412 },
    { "enableWaterNormalMapping", 9420 },
    { "enableWaterReflection", 9388 },
    { "exposure", 7988 },
    { "foamIntensity", 9348 },
    { "fogColor", 8160 },
    { "fogEnd", 8152 },
    { "fogIntensity", 8172 },
    { "fogStart", 8148 },
    { "frameExposure", 8024 },
    { "giBounces", 8128 },
    { "giIntensity", 8124 },
    { "hasNormalMap", 8028 },
    { "hasSceneDepth", 9400 },
    { "hasShadowMap", 8180 },
    { "hasSkyTexture", 9396 },
    { "horizonColor", 9376 },
    { "iblIntensity", 8100 },
    { "impostor", 7936 },
    { "impostorCols", 9432 },
    { "impostorHeight", 9444 },
    { "impostorRows", 9436 },
    { "impostorWidth", 9440 },
    { "instanceBillboard", 1292 },
    { "instancePoints", 1288 },
    { "invViewProjection", 8784 },
    { "isInstanced", 1280 },
    { "isSkinned", 1632 },
    { "jitter", 7792 },
    { "lightColor", 9312 },
    { "lightCount", 7808 },
    { "lightDirection", 9296 },
    { "lightIntensity", 9324 },
    { "lightPos", 9280 },
    { "lightSpaceMatrix", 1440 },
    { "materialAlpha", 8012 },
    { "metallic", 7980 },
    { "model", 1312 },
    { "noiseIntensity", 8540 },
    { "noiseOctaves", 8536 },
    { "noiseScale", 8532 },
    { "normalStrength", 8032 },
    { "occlusionStrength", 8036 },
    { "poseBankFrames", 9428 },
    { "prevModel", 1504 },
    { "prevViewProjection", 1568 },
    { "projection", 8576 },
    { "rayFrame", 8524 },
    { "rayLampRadius", 8516 },
    { "rayOcclusion", 8508 },
    { "rayOcclusionStrength", 8512 },
    { "rayReach", 8520 },
    { "rayShadows", 8500 },
    { "reflectivity", 8016 },
    { "roughness", 7984 },
    { "screenSize", 7800 },
    { "shadowDirection", 8192 },
    { "shadowIntensity", 8184 },
    { "shadowSoftness", 8188 },
    { "sheenColor", 8064 },
    { "sheenRoughness", 8076 },
    { "skyColor", 9360 },
    { "skyOvercast", 8724 },
    { "skyOvercastColor", 8736 },
    { "skyProcedural", 8720 },
    { "specularColor", 7968 },
    { "ssaoIntensity", 8860 },
    { "ssaoRadius", 8856 },
    { "ssrRoadHeight", 8848 },
    { "ssrStrength", 8852 },
    { "subpixelQuality", 8768 },
    { "sunAngle", 8504 },
    { "taaBlend", 8868 },
    { "texelSize", 8752 },
    { "time", 8872 },
    { "transmissionFactor", 8084 },
    { "useInstanceColor", 1284 },
    { "view", 8640 },
    { "viewDepth", 7920 },
    { "viewDistance", 7944 },
    { "viewPos", 1296 },
    { "viewProjection", 1376 },
    { "volumetricIntensity", 8108 },
    { "volumetricScattering", 8116 },
    { "volumetricSteps", 8112 },
    { "waterBaseColor", 9328 },
    { "waterDepthFade", 9404 },
    { "waterDistortionIntensity", 9416 },
    { "waterLevel", 9356 },
    { "waterNormalIntensity", 9424 },
    { "waterOpacity", 9340 },
    { "waterPlaneHeight", 9352 },
    { "waterReflectionIntensity", 9392 },
    { "waterShoreFoam", 9408 },
    { "waveAmplitudes", 8960 },
    { "waveDirections", 8896 },
    { "waveFrequencies", 9024 },
    { "waveHeightMultiplier", 8880 },
    { "wavePhases", 9152 },
    { "waveRandomness", 8884 },
    { "waveSpeedMultiplier", 8876 },
    { "waveSpeeds", 9088 },
    { "waveSteepness", 9216 },
    { "wetness", 8020 },
};

#define AE3D_VK_UNIFORM_SLOT_COUNT 148

static inline int ae3d_vk_uniform_offset(const char *name) {
    int low = 0;
    int high = AE3D_VK_UNIFORM_SLOT_COUNT - 1;
    if (!name) return -1;
    while (low <= high) {
        int mid = (low + high) / 2;
        int order = strcmp(name, ae3d_vk_uniform_slots[mid].name);
        if (order == 0) return ae3d_vk_uniform_slots[mid].offset;
        if (order < 0) high = mid - 1; else low = mid + 1;
    }
    return -1;
}

static inline void ae3d_vk_set_float(ae3d_vk_scene *s, int offset, float v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_int(ae3d_vk_scene *s, int offset, int v) {
    memcpy(s->bytes + offset, &v, sizeof(v));
}
static inline void ae3d_vk_set_vec3(ae3d_vk_scene *s, int offset, double x, double y, double z) {
    float v[3];
    v[0] = (float)x; v[1] = (float)y; v[2] = (float)z;
    memcpy(s->bytes + offset, v, sizeof(v));
}
static inline void ae3d_vk_set_mat4(ae3d_vk_scene *s, int offset, const double *m) {
    float v[16];
    int i;
    for (i = 0; i < 16; i++) v[i] = (float)m[i];
    memcpy(s->bytes + offset, v, sizeof(v));
}

#endif
